//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM
    {
        public int Id { get; set; }
        public string SMS { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
