

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _18_Jun_2021.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AccountEntities1 : DbContext
{
    public AccountEntities1()
        : base("name=AccountEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

}

}

