//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_Jun_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public int Id { get; set; }
        public string TargetStation { get; set; }
        public string StationInfo { get; set; }
        public string PhoneNum { get; set; }
    }
}
